# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xecret < Formula
  desc "Open-source, developer-first secret management"
  homepage "https://xecret.playxoft.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.0/xecret_0.1.0_darwin_amd64.tar.gz"
      sha256 "8f4a00f8b7078562d1ad500b63d98b34028376a464de5f87bc214cf9d7570892"

      define_method(:install) do
        bin.install "xecret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.0/xecret_0.1.0_darwin_arm64.tar.gz"
      sha256 "7c228a0867c708f2d0de62cf866418f2fb8d24a92be9358b7e4e24fdae1007f9"

      define_method(:install) do
        bin.install "xecret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.0/xecret_0.1.0_linux_amd64.tar.gz"
      sha256 "a3ab81fad2f3f71908f1c7ef4d6cce1b2083c65174f110d6f5411412974bd5bc"
      define_method(:install) do
        bin.install "xecret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.0/xecret_0.1.0_linux_arm64.tar.gz"
      sha256 "38307332204a37cb1a066b7e18ca518fce4f44ecd773c1e8f5cf11bc9948c728"
      define_method(:install) do
        bin.install "xecret"
      end
    end
  end

  test do
    system "#{bin}/xecret", "version"
  end
end
