# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xecret < Formula
  desc "Open-source, developer-first secret management"
  homepage "https://xecret.playxoft.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/playxoft/xecret/releases/download/v0.2.0/xecret_0.2.0_darwin_amd64.tar.gz"
      sha256 "1feab06db98e069816aeb1abdeff67e4e1a15a2e0cbc88af70018877c9cd3a30"

      define_method(:install) do
        bin.install "xecret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/playxoft/xecret/releases/download/v0.2.0/xecret_0.2.0_darwin_arm64.tar.gz"
      sha256 "3c2fccbb15f97d1314211cb6795a2c52f04f2b76616f36423a7740d898586f4a"

      define_method(:install) do
        bin.install "xecret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/playxoft/xecret/releases/download/v0.2.0/xecret_0.2.0_linux_amd64.tar.gz"
      sha256 "71ce1f870359366ad30695ea8d0b5c06155d990b8ee9222a182f24fcd8078564"
      define_method(:install) do
        bin.install "xecret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/playxoft/xecret/releases/download/v0.2.0/xecret_0.2.0_linux_arm64.tar.gz"
      sha256 "1b9fbc2624be5f7705abb3640493ade0053706dcf44692ccf2cd415525be97b2"
      define_method(:install) do
        bin.install "xecret"
      end
    end
  end

  test do
    system "#{bin}/xecret", "version"
  end
end
