# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xecret < Formula
  desc "Open-source, developer-first secret management"
  homepage "https://xecret.playxoft.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.2/xecret_0.1.2_darwin_amd64.tar.gz"
      sha256 "139c58f0786e0894f3e80aa236c60b620217361d6b159a1621b3a0ab85cc3023"

      define_method(:install) do
        bin.install "xecret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.2/xecret_0.1.2_darwin_arm64.tar.gz"
      sha256 "e0d1d75e76ea7f6db838ea9bc9e25461b774c5902423092f981c657986fd0491"

      define_method(:install) do
        bin.install "xecret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.2/xecret_0.1.2_linux_amd64.tar.gz"
      sha256 "6678a16441ef97d2a36b7dd7e552ba587836028d3d334f803384b76f177f2913"
      define_method(:install) do
        bin.install "xecret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/playxoft/xecret/releases/download/v0.1.2/xecret_0.1.2_linux_arm64.tar.gz"
      sha256 "093a407ae3666e889af47d4f7041962928a71e6c9d16b3ad34c59e062737a8ad"
      define_method(:install) do
        bin.install "xecret"
      end
    end
  end

  test do
    system "#{bin}/xecret", "version"
  end
end
